### ISSUE TITLE
[STABILITY] - Discover If Test harness Instability is Causing CI Flakiness

### ISSUE THREAD

**Issue by jparr721** [EspressoSystems/HotShot#2727] opened 2024-03-08 01:04 UTC
### What is this task and why do we need to work on it?

Ref: https://github.com/EspressoSystems/HotShot/pull/2716#issuecomment-1984394847

>My only concern is: we did have a failure (today) in `test_consensus_task`: https://github.com/EspressoSystems/HotShot/actions/runs/8192042140/job/22402665222#step:7:1863 and this was non-deterministic (and very rare). 

>I don't know if the failure is exposing a timing issue in the old test harness (which is fine) or the consensus logic (bad), but I want to suggest we keep the old tests around for a while (especially since we'll be adjusting the log level soon, which should give us a much better idea of why it failed). 

>I think we could have e.g. `test_consensus_task_old`, with a comment to delete it once we know why that failure happened, or if the consensus task changes and the test needs to be rewritten or anyway, or a few months have passed without the failure showing up again.

This is an important task as we eventually want to move to the newer testing framework as is it easier to follow and more maintainable. However, until we know the cause of the regressions that we occasionally see in CI, we do not quite want to delete the old tests just yet. The idea here is to figure out if the CI instability is indeed caused by the old test harness.

### What work will need to be done to complete this task?

We need to verify what the root cause of the CI failures is, which may be decidedly non-trivial, but a good first step would be to simply check if the problem originates with consensus itself, or with the old testing infrastructure.

### What are the acceptance criteria to close this issue?

We need to find the root cause of the CI problems and then simply delete the code postfixed with `old` in the test.

**Comment by bfish713** [comment] 2024-03-21 17:59
I think we can close this one, the old test is removed and I believe the cause of the issue

**Closed by bfish713** 2024-03-21 17:59 UTC
Labels: tech-debt, stability, cappuccino, cappuccino-sprint2
