### ISSUE TITLE
Refactor libP2P to enable DA committees

### ISSUE THREAD

**Issue by bfish713** [EspressoSystems/HotShot#846] opened 2023-01-06 14:28 UTC
- First we need to handle the simple case of static committee.  Each DA message will go only to the same subset of the network.  In the LibP2P layer we can probably just one topic for this and always use it
- The more challenging case is for dynamic committess.   We need to come up with a way to create subgroups/topics on the fly for each round/view.

**Comment by jbearer** [comment] 2023-05-09 15:54
Duplicate of #1065

**Closed by jbearer** 2023-05-09 15:54 UTC
Labels: da-networks, sprint2, sprint3
