### ISSUE TITLE
Update libp2p to use QUIC

### ISSUE THREAD

**Issue by elliedavidson** [EspressoSystems/HotShot#1624] opened 2023-08-25 15:29 UTC
https://github.com/libp2p/rust-libp2p/blob/master/transports/quic/CHANGELOG.md

**Comment by DieracDelta** [comment] 2023-08-25 18:17
I think this is a duplicate of https://github.com/EspressoSystems/HotShot/issues/725. Should I close #725?

**Comment by elliedavidson** [comment] 2023-08-25 18:20
> I think this is a duplicate of #725. Should I close #725?

Yes, that sounds good.

**Closed** 2023-08-31 18:50 UTC
